# This is a basic workflow to help you get started with Actions

name: ARM Runner Test

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          curl -O -L https://github.com/actions/runner/releases/download/v2.275.1/actions-runner-linux-arm-2.275.1.tar.gz
          tar xzf ./actions-runner-linux-arm-2.275.1.tar.gz
          ls -l
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - uses: docker://multiarch/ubuntu-core:armhf-focal
        with:
          args: 'bash -c "./bin/installdependencies.sh && ./config.sh --help && ./config.sh --unattended --url ${{github.event.repository.html_url}} --token ${{secrets.RUNNER_REGISTER_TOKEN}} --replace && ./run.sh --once && ./config.sh remove --token ${{secrets.RUNNER_REGISTER_TOKEN}}"'
        env:
          RUNNER_ALLOW_RUNASROOT: 1
