name: CI


on: [push, pull_request]

jobs:
  build:
#    services:
#      clickhouse:
#        image: yandex/clickhouse-server
#        ports:
#          - 9000:9000
#        volumes:
#          - /:/var/lib/clickhouse
    #container:
    #  image: alpine:3.11.5
    runs-on: self-hosted
    #runs-on: [ubuntu-latest]
    #runs-on: [windows-latest]
    env:
      DYLD_INSERT_LIBRARIES1: /test/test/test
    steps:
    - name: Show the proc directory
      run: |
        echo 1
    - name: Run a one-line script
      run: echo Hello, world!
    #- name: Run a multi-line script
    #  run: |
    #    docker run -t ubuntu:18.04 ps
    #    docker run -t ubuntu:18.04 echo $(tty)
    - run: |
        echo  ${{ secrets.GITHUB_TOKEN }} | od -t x1
        echo  ${{ github.Token }} | od -t x1
    - run: |
        find --help
        where find
      shell: cmd
    - uses: actions/github-script@0.3.0
      with:
        debug: true
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log("hello")
          const content = await github.repos.getContents({
            owner: 'TingluoHuang',
            repo: 'main',
            path: 'action.yml'
          })
          console.log(content)
          console.log(content.data.content)
          console.log(Buffer.from(content.data.content, 'base64').toString())
          
