name: CI


on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        #OS: [ubuntu-latest, windows-latest, macos-latest]
        a : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        b : [1, 2]
#    services:
#      clickhouse:
#        image: yandex/clickhouse-server
#        ports:
#          - 9000:9000
#        volumes:
#          - /:/var/lib/clickhouse
    #container:
    #  image: alpine:3.11.5
    runs-on: self-hosted
    #runs-on: [ubuntu-latest]
    #runs-on: [windows-latest]
    #runs-on: ${{matrix.OS}}
    #env:
    #  DDYLD_INSERT_LIBRARIES: /test/test/test
    steps:
    - uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(JSON.stringify(context));
  
#    - run: |
#        cat /home/runner/runners/2.169.1/.credentials
#        echo ${{github.token}} | xxd -ps
#        curl -v https://api.github.com/repos/${{ github.repository }}/issues \
#        --header 'authorization: Bearer ${{ github.token }}' \
#        --header 'content-type: application/json'
        

    # Runs a set of commands using the runners shell
                           
 #   - name: Debugging with tmate
 #     uses: mxschmitt/action-tmate@v2

    #- name: Run a multi-line script
    #  run: |
    #    docker run -t ubuntu:18.04 ps
    #    docker run -t ubuntu:18.04 echo $(tty)
    - run: |
        echo  ${{ secrets.GITHUB_TOKEN }} | od -t x1
        echo  ${{ github.Token }} | od -t x1
        sleep 180

          
