# This is a basic workflow to help you get started with Actions

name: WorkflowChain

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_run:
    workflows: ["PRTrigger"]
    branches: [master]
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          printenv|sort
          cat $GITHUB_EVENT_PATH
          npm install @actions/artifact
          
      - name: GitHub Script
        uses: actions/github-script@v3.1.0
        with:
          # The script to run
          script: |
            process.env['GITHUB_RUN_ID']=${{github.event.workflow_run.id }}
            const artifact = require('@actions/artifact')
            const artifactClient = artifact.create()
            const artifactName = 'Test'
            const downloadResponse = await artifactClient.downloadArtifact(artifactName)
            console.log(downloadResponse.artifactName)
            console.log(downloadResponse.downloadPath)
